# Default values for chaos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: chaos

targetNamespace: shop

chaos-mesh:
  dashboard:
    create: false
  chaosDaemon:
    runtime: containerd
    socketPath: /run/containerd/containerd.sock