apiVersion: v2
name: shop
description: A sample distributed .NET system for Chaos Engineering
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server/
  - name: postgresql
    alias: orderdb
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    alias: inventorydb
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami