apiVersion: v1
kind: Secret
metadata:
  name: inventorydb-psql-connection
type: Opaque
stringData:
  connectionString: "Host=target-inventorydb;Database=inventory;Username=postgres;Password=adminpass"
