apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-mesh-default-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: chaos-controller-manager
    namespace: chaos
roleRef:
  kind: ClusterRole
  name: chaos-mesh
  apiGroup: rbac.authorization.k8s.io
